### PR TITLE
Removing abort_when_done from FGEN example.

### PR DESCRIPTION
**Pull request by DelpireNI**
Signed-off-by: Chris Delpire <chris.delpire@ni.com>

- [X] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-python/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Removes the abort_when_done parameter from our FGEN example measurement. We tested with hardware and determined that this parameter did not have any effect. 

I also updated the measui to remove the control for this parameter, and I tried updating the seq file. **Can someone else pull this down and validate it on their machine?** The diff is gnarly.

### Why should this Pull Request be merged?

We shouldn't ship an example with a non-functional parameter.

### What testing has been done?

Successfully ran TestStand sequence using simulated PXIe-5423 (2CH).

[AB#2273840](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2273840)

### CODE REVIEW

**Comment by bkeryan** [comment]
We should decide whether to close https://github.com/ni/measurementlink-python/issues/152 . This doesn't make my intended use case work, but it at least removes my non-working implementation of that use case.

**Comment by bkeryan** [comment]
When I diff the TS sequence I get

```

**Comment by DelpireNI** [comment]
> When I diff the TS sequence I get
> 
> ```
> Type 'NI_MeasurementParameter' in NIFgenStandardFunction.seq (D:\dev\measurementlink-python\examples\nifgen_standard_function\NIFgenStandardFunction.seq) is different from the currently loaded type 'NI_MeasurementParameter'.
> 
> Currently Loaded Type
> Version 21.0.5.4
> Last modified: 11/21/2022 8:48:19 AM (Older)
> Category: UserTypes
> Location(s): NIFgenStandardFunction.seq
> 
> Type in File
> Version 21.0.5.4 (Modified)
> Last modified: 1/11/2023 1:24:55 PM (Newer)
> Category: UserTypes
> Location: NIFgenStandardFunction.seq
> 
> Summary of Differences:
> 
> NI_MeasurementParameter (Value, Flag, or Representation Difference)
> ```

@bkeryan I updated the seq file using the latest build which included the change to lock the step type with a password. It looks like that resulted in a change in the seq file. I think that's why its saying `NI_MeasurementParameter ` is different. I was talking to @dixonjoel  about this previous. I think we should probably save all the .seq files with our final build once that's available.

**Comment by dixonjoel** [comment]
> We should decide whether to close #152 . This doesn't make my intended use case work, but it at least removes my non-working implementation of that use case.

So does the generation just keep running indefinitely?

**Comment by DelpireNI** [comment]
> > We should decide whether to close #152 . This doesn't make my intended use case work, but it at least removes my non-working implementation of that use case.
> 
> So does the generation just keep running indefinitely?

The opposite. Whether checked or unchecked, I always lost my sine wave after the time elapsed.

**Comment by bkeryan** [comment]
Other than the type version, the TS diff looks ok:
image

**Comment by bkeryan** [comment]
> Edit: I guess if that's the only change, should I just revert it? Its unclear to me whether the boolean appears because its saved to the seq file, or if TestStand will just remove it because it is no longer a parameter.

TS won't automatically remove measurement service parameters. You had to click the "refresh parameters" button to do that. Updating the sequence is good because it prevents the TS measurement edit panel from displaying a mismatched parameters error.

**Review by bkeryan — APPROVED** [review]

**Review by dixonjoel — APPROVED** [review]

**Pull request merged**
